spring:
  application:
      name: spring-boot-redis
  # 配置Redis的连接密码
#  redis:
#    password:
#    host:
#    database: 3
#    jedis:
#       pool:
#          max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
#          max-idle: 10   # 连接池中的最大空闲连接
#          min-idle: 5    # 连接池中的最小空闲连接
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/seat_select?characterEncoding=utf8
      #最大活跃数
      max-active: 20
      #初始化数量
      initial-size: 1
      #最大连接等待超时时间
      max-wait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      min-evictable-idle-time-millis: 300000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
      filter:
              commons-log:
                connection-logger-name: stat,log4j,wall
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

